version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    networks:
      - red
  frontend:
     build:
       context: ./frontend
       dockerfile: ./Dockerfile
     ports:
       - 3333:3333
     networks:
       - red
  db_egresados:
    image: mariadb
    hostname: db_egresados
    environment:
      MYSQL_ROOT_PASSWORD: "qrj781234Nahm1"   #colocar password
      MYSQL_DATABASE: egresados
      MYSQL_USER: egresados_manager
      MYSQL_PASSWORD: "mkJu1354dnppl"  #colocar password
    volumes:
      - ./database/egresados.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    ports:
      - 3308:3308
    networks:
      - red
volumes:
   data:
     external: false
networks:
    red:
        name: red
