@startuml
!define AWSPUML https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v17.0.0/dist


!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.1.2/sprites

!define SPRITE(name, url) <img:sprites/{url}.png&scale=2.5>
[Gestión] --> [Usuarios]
[Usuarios] --> [API de Usuarios]
[Usuarios] <-- [Estudiantes]
[Estudiantes] --> [API de Estudiantes]
[Comprobantes] --> [API de Comprobantes]
[Usuarios] <-- [Comprobantes]
[Gestión] --> [API de Gestión]
@enduml
